cscourses/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from cscourses import db


class User(UserMixin, db.Model):
    __tablename__ = "user"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text)
    email = db.Column(db.Text, unique=True)
    password = db.Column(db.Text)
    user_type = db.Column(db.String(10), nullable=False)

    __mapper_args__ = {
        "polymorphic_identity": "user",
        "polymorphic_on": user_type
    }

    def __repr__(self):
        return '<User Email: {}, Name: {}>'.format(self.email, self.name)

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)


class Student(User):
    __tablename__ = 'student'
    id = db.Column(None, db.ForeignKey('user.id'), primary_key=True)
    student_ref = db.Column(db.Integer)
    grades = db.relationship('Grade', backref='students')

    __mapper_args__ = {"polymorphic_identity": "student"}

    def __repr__(self):
        return '<Student ID: {}, name: {}>'.format(self.student_ref, self.name)


class Teacher(User):
    __tablename__ = 'teacher'
    id = db.Column(None, db.ForeignKey('user.id'), primary_key=True)
    teacher_ref = db.Column(db.Text, nullable=False)
    title = db.Column(db.Text)
    courses = db.relationship('Course', backref='teachers')

    __mapper_args__ = {"polymorphic_identity": "teacher"}

    def __repr__(self):
        return '<Teacher ID: {}, Title: {}, Name: {}.>'.format(self.teacher_ref, self.title, self.name)


class Course(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    course_code = db.Column(db.Integer, nullable=False)
    name = db.Column(db.Text, nullable=False)
    teacher_id = db.Column(db.Integer, db.ForeignKey(Teacher.id), nullable=False)
    grades = db.relationship('Grade', backref='courses')

    def __repr__(self):
        return '<Course code: {}, name: {}>'.format(self.code, self.name)


class Grade(db.Model):
    student_id = db.Column(db.Integer, db.ForeignKey(Student.id), nullable=False, primary_key=True)
    course_id = db.Column(db.Integer, db.ForeignKey(Course.id), nullable=False, primary_key=True)
    grade = db.Column(db.Text)

    def __repr__(self):
        return '<Grade {}>'.format(self.grade)

cscourses/__init__.py
from flask import Flask, render_template
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()
login_manager = LoginManager()
login_manager.login_view = 'auth.login'


def page_not_found(e):
    return render_template('errors/404.html'), 404


def internal_server_error(e):
    return render_template('errors/500.html'), 500


def create_app(config_class=None):
    """
    Creates an application instance to run
    :return: A Flask object
    """
    app = Flask(__name__)

    # Configure app wth the settings from config.py
    app.config.from_object(config_class)

    # Initialise plugins
    db.init_app(app)
    login_manager.init_app(app)

    from cscourses.models import Teacher, Student, Course, Grade
    with app.app_context():
        db.drop_all()
        db.create_all()

    # Register error handlers
    app.register_error_handler(404, page_not_found)
    app.register_error_handler(500, internal_server_error)

    # Register Blueprints
    from cscourses.main.routes import bp_main
    app.register_blueprint(bp_main)

    from cscourses.auth.routes import bp_auth
    app.register_blueprint(bp_auth)

    return app

cscourses/main/routes.py
from flask import render_template, Blueprint, request, flash, redirect, url_for
from flask_login import current_user, login_required
from sqlalchemy import or_
from sqlalchemy.orm import with_polymorphic

from cscourses import db
from cscourses.models import Course, Student, Teacher, User

bp_main = Blueprint('main', __name__)


@bp_main.route('/')
def index(name=""):
    if current_user.is_authenticated:
        name = current_user.name
    return render_template("main/index.html", name=name)


@bp_main.route('/courses', methods=['GET'])
def courses():
    courses = Course.query.join(Teacher).with_entities(Course.course_code, Course.name,
                                                       Teacher.name.label('teacher_name')).all()
    return render_template("main/courses.html", courses=courses)


@bp_main.route('/search', methods=['POST', 'GET'])
def search():
    if request.method == 'POST':
        term = request.form['search_term']
        if term == "":
            flash("Enter a name to search for")
            return redirect(url_for('main.index'))
        users = with_polymorphic(User, [Student, Teacher])
        results = db.session.query(users).filter(
            or_(users.Student.name.contains(term), users.Teacher.name.contains(term))).all()
        if not results:
            flash("No students found with that name.")
            return redirect(url_for('main.index'))
        return render_template('main/search_results.html', results=results)
    else:
        return redirect(url_for('main.index'))


@bp_main.route('/view_profile/', methods=['POST', 'GET'])
@login_required
def view_profile():
    result = db.session.query(User).filter(User.id == current_user.id).first()
    if isinstance(result, Student):
        return render_template('main/view_profile.html', profile=result, type='student')
    else:
        return render_template('main/view_profile.html', profile=result, type='teacher')

cscourses/templates/_formhelpers.html
{% macro render_field(field) %}
    <dt>{{ field.label }}
    <dd>{{ field(**kwargs)|safe }}
        {% if field.errors %}
            <ul class="alert-warning list-unstyled">
                {% for error in field.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </dd>
{% endmacro %}

cscourses/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{{ title }}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}">
</head>
<body>
<nav class="navbar navbar-expand bg-primary navbar-dark">
    <a class="navbar-brand" href="#">CS Courses</a>
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" id=main-link href="{{ url_for('main.index') }}">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id=signup-link href="{{ url_for('auth.signup') }}">Sign up</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id=courses-link href="{{ url_for('main.courses') }}">Courses</a>
        </li>
        {% if current_user.is_anonymous %}
            <li class="nav-item">
                <a class="nav-link" id=login-link href="{{ url_for('auth.login') }}">Log in</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" id=logout-link href="{{ url_for('auth.logout') }}">Logout</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id=profile-link href="{{ url_for('main.view_profile') }}">My profile</a>
            </li>
        {% endif %}
    </ul>
    <form class="form-inline ml-auto" action="search" method="post">
        <input class="form-control" type="search" placeholder="Enter student name" aria-label="Search"
               name="search_term">
        <button class="btn btn-primary btn-outline-light" type="submit">Search</button>
    </form>
</nav>
<br>
<div role=main class="container">
    {# Displays flashed messages on a page #}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul class="alert-warning list-unstyled">
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}
    {% block content %}
        {# Child pages add page specific content here #}
    {% endblock %}
</div>
</body>
</html>

cscourses/templates/main/courses.html
{% extends "base.html" %}
{% block title %}Courses{% endblock %}
{% block content %}
    {% if courses|length %}
        <table class="table">
            <thead class="thead-dark">
            <tr>
                <th scope="col">Code</th>
                <th scope="col">Course Name</th>
                <th scope="col">Teacher</th>
            </tr>
            </thead>
            <tbody>
            {% for course in courses %}
                <tr>
                    <td>{{ course.course_code }}</td>
                    <td>{{ course.name }}</td>
                    <td>{{ course.teacher_name }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Sorry, no courses are available at this time</p>
    {% endif %}
{% endblock %}

cscourses/templates/main/index.html
{# Inherit a parent template called base.html #}
{% extends "base.html" %}
{# Add the title for this page #}
{% block title %}Home{% endblock %}
{# Add the content for this page #}
{% block content %}
    <h1>Welcome {{ name }}</h1>
{% endblock %}

cscourses/templates/main/search_results.html
{% extends "base.html" %}
{% block title %}Search results{% endblock %}
{% block content %}
    {% if results|length %}
        {# Variable is not empty #}
        <table class="table">
            <thead class="thead-dark">
            <tr>
                <th scope="col">Student name</th>
                <th scope="col">Email</th>
            </tr>
            </thead>
            <tbody>
            {% for result in results %}
                <tr>
                    <td>{{ result.name }}</td>
                    <td>{{ result.email }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        {# Variable is empty #}
        <p>Sorry, no students found</p>
    {% endif %}
{% endblock %}

cscourses/templates/main/view_profile.html
{% extends "base.html" %}
{% block title %}Profile{% endblock %}
{% block content %}
    <h3>Profile details</h3>
    <p>Name: {{ profile.name }}</p>
    <p>Email address: {{ profile.email }}</p>
    {% if type ==  "student" %}
        <p>College identifier: {{ profile.student_ref }}</p>
        <p>Account type: Student</p>
    {% else %}
        <p>College identifier: {{ profile.teacher_ref }}</p>
        <p>Account type: Teacher</p>
    {% endif %}
{% endblock %}